name: ci-checks
on: [push, pull_request]
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - shell: bash
        run: |
          sudo apt-get install clang-format-11
      - shell: bash
        run: |
          clang-format-11 --version
      - shell: bash
        run: |
          ! clang-format-11 *.h *.cpp -style=file --output-replacements-xml | grep "<replacement "
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: make
